/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Bryan
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritoriojDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        clientesjMenuItem = new javax.swing.JMenuItem();
        proveedoresjMenuItem = new javax.swing.JMenuItem();
        productosjMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritoriojDesktopPaneLayout = new javax.swing.GroupLayout(escritoriojDesktopPane);
        escritoriojDesktopPane.setLayout(escritoriojDesktopPaneLayout);
        escritoriojDesktopPaneLayout.setHorizontalGroup(
            escritoriojDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
        );
        escritoriojDesktopPaneLayout.setVerticalGroup(
            escritoriojDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        jMenu1.setText("Ingresar");

        clientesjMenuItem.setText("Clientes");
        clientesjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesjMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(clientesjMenuItem);

        proveedoresjMenuItem.setText("Proveedores");
        proveedoresjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedoresjMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(proveedoresjMenuItem);

        productosjMenuItem.setText("Productos");
        productosjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productosjMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(productosjMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Gestión");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritoriojDesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritoriojDesktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientesjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesjMenuItemActionPerformed
        ClientesVista cv = new ClientesVista();
        escritoriojDesktopPane.add(cv);
        cv.setVisible(true);
    }//GEN-LAST:event_clientesjMenuItemActionPerformed

    private void proveedoresjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedoresjMenuItemActionPerformed
        ProveedoresVista pv = new ProveedoresVista();
        escritoriojDesktopPane.add(pv);
        pv.setVisible(true);
    }//GEN-LAST:event_proveedoresjMenuItemActionPerformed

    private void productosjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productosjMenuItemActionPerformed
        ProductosVista pv = new ProductosVista();
        escritoriojDesktopPane.add(pv);
        pv.setVisible(true);
    }//GEN-LAST:event_productosjMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem clientesjMenuItem;
    private javax.swing.JDesktopPane escritoriojDesktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem productosjMenuItem;
    private javax.swing.JMenuItem proveedoresjMenuItem;
    // End of variables declaration//GEN-END:variables
}
