/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controller.PersonController;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.PersonModel;

/**
 *
 * @author Bryan
 */
public final class PersonView extends javax.swing.JInternalFrame {

    PersonController controller;
    PersonModel model;

    /**
     * Creates new form ClientesVista
     */
    public PersonView() {
        initComponents();
        controller = new PersonController();
        model = new PersonModel();
        loadPeople("");
    }

    public void loadPeople(String searchTerm) {
        controller.setSearch(searchTerm);
        DefaultTableModel tableModel = model.selectPeople(controller);
        personjTable.setModel(tableModel);
    }

    public void cleanForm() {
        idjTextField.setText("");
        documentjTextField.setText("");
        name1jTextField.setText("");
        name2jTextField.setText("");
        lastName1jTextField.setText("");
        lastName2jTextField.setText("");
        sexjTextField.setText("");
        birthdatejTextField.setText("");
        placeOfBirthjTextField.setText("");
        agejSpinner.setValue(0);
        nationalityjTextField.setText("");
        cellphonejTextField.setText("");
        emailjTextField.setText("");
        spouseNamejTextField.setText("");
        spouseDocumentjTextField.setText("");
        spouseBirthdatejTextField.setText("");
        spouseOccupationjTextField.setText("");
        fatherNamejTextField.setText("");
        fatherDocumentjTextField.setText("");
        fatherBirthdatejTextField.setText("");
        fatherOccupationjTextField.setText("");
        motherNamejTextField.setText("");
        motherDocumentjTextField.setText("");
        motherBirthdatejTextField.setText("");
        motherOccupationjTextField.setText("");
    }

    public boolean validateFields(String... data) {
        boolean correct = false;

        for (String datum : data) {
            if (datum.length() == 0) {
                JOptionPane.showMessageDialog(null, "Formulario vacío", "Error", JOptionPane.ERROR_MESSAGE);
                return correct;
            }
        }

        correct = true;
        return correct;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchPersonjTextField = new javax.swing.JTextField();
        searchjButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        personjTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        insertjButton = new javax.swing.JButton();
        updatejButton = new javax.swing.JButton();
        deletejButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        idjTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        documentjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        name1jTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        name2jTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lastName1jTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lastName2jTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        sexjTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        birthdatejTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        placeOfBirthjTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nationalityjTextField = new javax.swing.JTextField();
        cellphonejTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        emailjTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        spouseNamejTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        spouseDocumentjTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        spouseBirthdatejTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        spouseOccupationjTextField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        fatherNamejTextField = new javax.swing.JTextField();
        fatherDocumentjTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        fatherBirthdatejTextField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        fatherOccupationjTextField = new javax.swing.JTextField();
        agejSpinner = new javax.swing.JSpinner();
        jLabel23 = new javax.swing.JLabel();
        motherNamejTextField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        motherDocumentjTextField = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        motherBirthdatejTextField = new javax.swing.JTextField();
        motherOccupationjTextField = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Clientes");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar"));

        jLabel1.setText("Buscar persona:");

        searchjButton.setText("Buscar");
        searchjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchPersonjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchjButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(searchPersonjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchjButton))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Personas"));

        personjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        personjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                personjTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(personjTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestión"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insertjButton.setText("Insertar");
        insertjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertjButtonActionPerformed(evt);
            }
        });
        jPanel3.add(insertjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 34, -1, -1));

        updatejButton.setText("Actualizar");
        updatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButtonActionPerformed(evt);
            }
        });
        jPanel3.add(updatejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 34, -1, -1));

        deletejButton.setText("Borrar");
        deletejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletejButtonActionPerformed(evt);
            }
        });
        jPanel3.add(deletejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 34, -1, -1));

        jLabel2.setText("ID:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 77, -1, -1));

        idjTextField.setEditable(false);
        jPanel3.add(idjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 74, 167, -1));

        jLabel3.setText("Cédula:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 117, -1, -1));
        jPanel3.add(documentjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 114, 167, -1));

        jLabel4.setText("Nombre 1:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 157, -1, -1));
        jPanel3.add(name1jTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 154, 167, -1));

        jLabel5.setText("Nombre 2:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 197, -1, -1));
        jPanel3.add(name2jTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 194, 167, -1));

        jLabel9.setText("Apellido 1:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 237, -1, -1));
        jPanel3.add(lastName1jTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 234, 167, -1));

        jLabel10.setText("Apellido 2:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 271, -1, -1));
        jPanel3.add(lastName2jTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 268, 167, -1));

        jLabel11.setText("Sexo:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 302, -1, -1));
        jPanel3.add(sexjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 299, 167, -1));

        jLabel6.setText("Fecha nacimiento:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));
        jPanel3.add(birthdatejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 167, -1));

        jLabel7.setText("Lugar nacimiento:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));
        jPanel3.add(placeOfBirthjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 167, -1));

        jLabel8.setText("Edad:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        jLabel12.setText("Nacionalidad:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));
        jPanel3.add(nationalityjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 167, -1));
        jPanel3.add(cellphonejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 167, -1));

        jLabel13.setText("Teléfono movil:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        jLabel14.setText("Correo:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 265, -1, -1));
        jPanel3.add(emailjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 265, 167, -1));

        jLabel15.setText("Nombre Conyuge:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));
        jPanel3.add(spouseNamejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 167, -1));

        jLabel16.setText("C.I. Conyuge:");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, -1, -1));
        jPanel3.add(spouseDocumentjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 150, -1));

        jLabel17.setText("Fecha nacimiento Conyuge:");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, -1, -1));
        jPanel3.add(spouseBirthdatejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, 150, -1));

        jLabel18.setText("Ocupación Conyuge:");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, -1, -1));
        jPanel3.add(spouseOccupationjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, 150, -1));

        jLabel19.setText("Nombre Padre:");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, -1, -1));
        jPanel3.add(fatherNamejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 190, 150, -1));

        fatherDocumentjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatherDocumentjTextFieldActionPerformed(evt);
            }
        });
        jPanel3.add(fatherDocumentjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 150, -1));

        jLabel20.setText("C.I. Padre:");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, -1, -1));

        jLabel21.setText("Fecha nacimiento Padre:");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 265, -1, -1));
        jPanel3.add(fatherBirthdatejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 265, 150, -1));

        jLabel22.setText("Ocupación Padre:");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, -1, -1));
        jPanel3.add(fatherOccupationjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 300, 150, -1));
        jPanel3.add(agejSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 80, -1));

        jLabel23.setText("Nombre Madre:");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 70, -1, -1));
        jPanel3.add(motherNamejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 70, 150, -1));

        jLabel24.setText("C.I. Madre:");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 110, -1, -1));

        motherDocumentjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motherDocumentjTextFieldActionPerformed(evt);
            }
        });
        jPanel3.add(motherDocumentjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 110, 150, -1));

        jLabel25.setText("Fecha nacimiento Madre:");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 150, -1, -1));
        jPanel3.add(motherBirthdatejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 150, 150, -1));
        jPanel3.add(motherOccupationjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 190, 150, -1));

        jLabel26.setText("Ocupación Madre:");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 190, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1233, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchjButtonActionPerformed
        String searchTerm = searchPersonjTextField.getText().trim();
        loadPeople(searchTerm);
    }//GEN-LAST:event_searchjButtonActionPerformed

    private void insertjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertjButtonActionPerformed
        String id = idjTextField.getText().trim();
        String document = documentjTextField.getText().trim();
        String name1 = name1jTextField.getText().trim();
        String name2 = name2jTextField.getText().trim();
        String lastName1 = lastName1jTextField.getText().trim();
        String lastName2 = lastName2jTextField.getText().trim();
        String sex = sexjTextField.getText().trim();
        String birthdate = birthdatejTextField.getText().trim();
        String placeOfBirth = placeOfBirthjTextField.getText().trim();
        String age = agejSpinner.getValue().toString();
        String nationality = nationalityjTextField.getText().trim();
        String cellphone = cellphonejTextField.getText().trim();
        String email = emailjTextField.getText().trim();
        String spouseName = spouseNamejTextField.getText().trim();
        String spouseDocument = spouseDocumentjTextField.getText().trim();
        String spouseBirthdate = spouseBirthdatejTextField.getText().trim();
        String spouseOccupation = spouseOccupationjTextField.getText().trim();
        String fatherName = fatherNamejTextField.getText().trim();
        String fatherDocument = fatherDocumentjTextField.getText().trim();
        String fatherBirthdate = fatherBirthdatejTextField.getText().trim();
        String fatherOccupation = fatherOccupationjTextField.getText().trim();
        String motherName = motherNamejTextField.getText().trim();
        String motherDocument = motherDocumentjTextField.getText().trim();
        String motherBirthdate = motherBirthdatejTextField.getText().trim();
        String motherOccupation = motherOccupationjTextField.getText().trim();

        if (id.length() != 0) {
            JOptionPane.showMessageDialog(null, "No puede insertar", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!validateFields(document, name1, name2, lastName1, lastName2, sex,
                birthdate, placeOfBirth, age, nationality, cellphone, email, spouseName,
                spouseDocument, spouseBirthdate, spouseOccupation, fatherName,
                fatherDocument, fatherBirthdate, fatherOccupation, motherName,
                motherDocument, motherBirthdate, motherOccupation)) {
            return;
        }

        controller.setDocument(document);
        controller.setName1(name1);
        controller.setName2(name2);
        controller.setLastName1(lastName1);
        controller.setLastName2(lastName2);
        controller.setSex(sex);
        controller.setBirthdate(birthdate);
        controller.setPlaceOfBirth(placeOfBirth);
        controller.setAge(Integer.parseInt(age));
        controller.setNationality(nationality);
        controller.setCellphone(cellphone);
        controller.setEmail(email);
        controller.setSpouseName(spouseName);
        controller.setSpouseDocument(spouseDocument);
        controller.setSpouseBirthdate(spouseBirthdate);
        controller.setSpouseOccupation(spouseOccupation);
        controller.setFatherName(fatherName);
        controller.setFatherDocument(fatherDocument);
        controller.setFatherBirthdate(fatherBirthdate);
        controller.setFatherOccupation(fatherOccupation);
        controller.setMotherName(motherName);
        controller.setMotherDocument(motherDocument);
        controller.setMotherBirthdate(motherBirthdate);
        controller.setMotherOccupation(motherOccupation);

        boolean result = model.insertPeople(controller);

        if (result) {
            JOptionPane.showMessageDialog(null, "Persona insertada", "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Persona no insertada", "Error", JOptionPane.ERROR_MESSAGE);
        }

        loadPeople("");
        cleanForm();
    }//GEN-LAST:event_insertjButtonActionPerformed

    private void personjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personjTableMouseClicked
        int row = personjTable.getSelectedRow();

        String id = personjTable.getValueAt(row, 0).toString();
        String document = personjTable.getValueAt(row, 1).toString();
        String name1 = personjTable.getValueAt(row, 2).toString();
        String name2 = personjTable.getValueAt(row, 3).toString();
        String lastName1 = personjTable.getValueAt(row, 4).toString();
        String lastName2 = personjTable.getValueAt(row, 5).toString();
        String sex = personjTable.getValueAt(row, 6).toString();
        String birthdate = personjTable.getValueAt(row, 7).toString();
        String placeOfBirth = personjTable.getValueAt(row, 8).toString();
        String age = personjTable.getValueAt(row, 9).toString();
        String nationality = personjTable.getValueAt(row, 10).toString();
        String cellphone = personjTable.getValueAt(row, 11).toString();
        String email = personjTable.getValueAt(row, 12).toString();
        String spouseName = personjTable.getValueAt(row, 13).toString();
        String spouseDocument = personjTable.getValueAt(row, 14).toString();
        String spouseBirthdate = personjTable.getValueAt(row, 15).toString();
        String spouseOccupation = personjTable.getValueAt(row, 16).toString();
        String fatherName = personjTable.getValueAt(row, 17).toString();
        String fatherDocument = personjTable.getValueAt(row, 18).toString();
        String fatherBirthdate = personjTable.getValueAt(row, 19).toString();
        String fatherOccupation = personjTable.getValueAt(row, 20).toString();
        String motherName = personjTable.getValueAt(row, 21).toString();
        String motherDocument = personjTable.getValueAt(row, 22).toString();
        String motherBirthdate = personjTable.getValueAt(row, 23).toString();
        String motherOccupation = personjTable.getValueAt(row, 24).toString();

        idjTextField.setText(id);
        documentjTextField.setText(document);
        name1jTextField.setText(name1);
        name2jTextField.setText(name2);
        lastName1jTextField.setText(lastName1);
        lastName2jTextField.setText(lastName2);
        sexjTextField.setText(sex);
        birthdatejTextField.setText(birthdate);
        placeOfBirthjTextField.setText(placeOfBirth);
        agejSpinner.setValue(Integer.valueOf(age));
        nationalityjTextField.setText(nationality);
        cellphonejTextField.setText(cellphone);
        emailjTextField.setText(email);
        spouseNamejTextField.setText(spouseName);
        spouseDocumentjTextField.setText(spouseDocument);
        spouseBirthdatejTextField.setText(spouseBirthdate);
        spouseOccupationjTextField.setText(spouseOccupation);
        fatherNamejTextField.setText(fatherName);
        fatherDocumentjTextField.setText(fatherDocument);
        fatherBirthdatejTextField.setText(fatherBirthdate);
        fatherOccupationjTextField.setText(fatherOccupation);
        motherNamejTextField.setText(motherName);
        motherDocumentjTextField.setText(motherDocument);
        motherBirthdatejTextField.setText(motherBirthdate);
        motherOccupationjTextField.setText(motherOccupation);
    }//GEN-LAST:event_personjTableMouseClicked

    private void updatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButtonActionPerformed
        String id = idjTextField.getText().trim();
        String document = documentjTextField.getText().trim();
        String name1 = name1jTextField.getText().trim();
        String name2 = name2jTextField.getText().trim();
        String lastName1 = lastName1jTextField.getText().trim();
        String lastName2 = lastName2jTextField.getText().trim();
        String sex = sexjTextField.getText().trim();
        String birthdate = birthdatejTextField.getText().trim();
        String placeOfBirth = placeOfBirthjTextField.getText().trim();
        String age = agejSpinner.getValue().toString();
        String nationality = nationalityjTextField.getText().trim();
        String cellphone = cellphonejTextField.getText().trim();
        String email = emailjTextField.getText().trim();
        String spouseName = spouseNamejTextField.getText().trim();
        String spouseDocument = spouseDocumentjTextField.getText().trim();
        String spouseBirthdate = spouseBirthdatejTextField.getText().trim();
        String spouseOccupation = spouseOccupationjTextField.getText().trim();
        String fatherName = fatherNamejTextField.getText().trim();
        String fatherDocument = fatherDocumentjTextField.getText().trim();
        String fatherBirthdate = fatherBirthdatejTextField.getText().trim();
        String fatherOccupation = fatherOccupationjTextField.getText().trim();
        String motherName = motherNamejTextField.getText().trim();
        String motherDocument = motherDocumentjTextField.getText().trim();
        String motherBirthdate = motherBirthdatejTextField.getText().trim();
        String motherOccupation = motherOccupationjTextField.getText().trim();

        if (id.length() == 0) {
            JOptionPane.showMessageDialog(null, "No puede actualizar", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!validateFields(document, name1, name2, lastName1, lastName2, sex,
                birthdate, placeOfBirth, age, nationality, cellphone, email, spouseName,
                spouseDocument, spouseBirthdate, spouseOccupation, fatherName,
                fatherDocument, fatherBirthdate, fatherOccupation, motherName,
                motherDocument, motherBirthdate, motherOccupation)) {
            return;
        }

        controller.setId(Integer.parseInt(id));
        controller.setDocument(document);
        controller.setName1(name1);
        controller.setName2(name2);
        controller.setLastName1(lastName1);
        controller.setLastName2(lastName2);
        controller.setSex(sex);
        controller.setBirthdate(birthdate);
        controller.setPlaceOfBirth(placeOfBirth);
        controller.setAge(Integer.parseInt(age));
        controller.setNationality(nationality);
        controller.setCellphone(cellphone);
        controller.setEmail(email);
        controller.setSpouseName(spouseName);
        controller.setSpouseDocument(spouseDocument);
        controller.setSpouseBirthdate(spouseBirthdate);
        controller.setSpouseOccupation(spouseOccupation);
        controller.setFatherName(fatherName);
        controller.setFatherDocument(fatherDocument);
        controller.setFatherBirthdate(fatherBirthdate);
        controller.setFatherOccupation(fatherOccupation);
        controller.setMotherName(motherName);
        controller.setMotherDocument(motherDocument);
        controller.setMotherBirthdate(motherBirthdate);
        controller.setMotherOccupation(motherOccupation);

        boolean result = model.updatePeople(controller);

        if (result) {
            JOptionPane.showMessageDialog(null, "Persona actualizada", "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Persona no actualizada", "Error", JOptionPane.ERROR_MESSAGE);
        }

        loadPeople("");
        cleanForm();
    }//GEN-LAST:event_updatejButtonActionPerformed

    private void deletejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletejButtonActionPerformed
        String id = idjTextField.getText().trim();

        if (id.length() == 0) {
            JOptionPane.showMessageDialog(null, "No se puede eliminar", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            controller.setId(Integer.parseInt(id));
            boolean result = model.deletePeople(controller);

            if (result) {
                JOptionPane.showMessageDialog(null, "Persona eliminada", "Información", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Persona no eliminada", "Error", JOptionPane.ERROR_MESSAGE);
            }

            loadPeople("");
            cleanForm();
        }
    }//GEN-LAST:event_deletejButtonActionPerformed

    private void fatherDocumentjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatherDocumentjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fatherDocumentjTextFieldActionPerformed

    private void motherDocumentjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motherDocumentjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motherDocumentjTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner agejSpinner;
    private javax.swing.JTextField birthdatejTextField;
    private javax.swing.JTextField cellphonejTextField;
    private javax.swing.JButton deletejButton;
    private javax.swing.JTextField documentjTextField;
    private javax.swing.JTextField emailjTextField;
    private javax.swing.JTextField fatherBirthdatejTextField;
    private javax.swing.JTextField fatherDocumentjTextField;
    private javax.swing.JTextField fatherNamejTextField;
    private javax.swing.JTextField fatherOccupationjTextField;
    private javax.swing.JTextField idjTextField;
    private javax.swing.JButton insertjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastName1jTextField;
    private javax.swing.JTextField lastName2jTextField;
    private javax.swing.JTextField motherBirthdatejTextField;
    private javax.swing.JTextField motherDocumentjTextField;
    private javax.swing.JTextField motherNamejTextField;
    private javax.swing.JTextField motherOccupationjTextField;
    private javax.swing.JTextField name1jTextField;
    private javax.swing.JTextField name2jTextField;
    private javax.swing.JTextField nationalityjTextField;
    private javax.swing.JTable personjTable;
    private javax.swing.JTextField placeOfBirthjTextField;
    private javax.swing.JTextField searchPersonjTextField;
    private javax.swing.JButton searchjButton;
    private javax.swing.JTextField sexjTextField;
    private javax.swing.JTextField spouseBirthdatejTextField;
    private javax.swing.JTextField spouseDocumentjTextField;
    private javax.swing.JTextField spouseNamejTextField;
    private javax.swing.JTextField spouseOccupationjTextField;
    private javax.swing.JButton updatejButton;
    // End of variables declaration//GEN-END:variables
}
