/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controller.StudentsController;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.StudentsModel;

/**
 *
 * @author Bryan
 */
public final class StudentsView extends javax.swing.JInternalFrame {

    StudentsController controller;
    StudentsModel model;

    /**
     * Creates new form ClientesVista
     */
    public StudentsView() {
        initComponents();
        controller = new StudentsController();
        model = new StudentsModel();
        loadStudents("");
    }

    public void loadStudents(String searchTerm) {
        controller.setSearch(searchTerm);
        DefaultTableModel tableModel = model.selectStudents(controller);
        studentsjTable.setModel(tableModel);
    }

    public void cleanForm() {
        idjTextField.setText("");
        documentjTextField.setText("");
        namejTextField.setText("");
        lastNamejTextField.setText("");
        grade1jTextField.setText("");
        grade2jTextField.setText("");
        grade3jTextField.setText("");
    }

    public boolean validateFields(String document, String name, String lastName, String grade1, String grade2, String grade3) {
        boolean correct = false;

        if (document.length() == 0
                || name.length() == 0
                || lastName.length() == 0
                || grade1.length() == 0
                || grade2.length() == 0
                || grade3.length() == 0) {

            JOptionPane.showMessageDialog(null, "Formulario vacío", "Error", JOptionPane.ERROR_MESSAGE);
            return correct;
        }

        if (document.length() != 10 || !document.matches("[0-9]{10}")) {
            JOptionPane.showMessageDialog(null, "Número de cédula inválido", "Error", JOptionPane.ERROR_MESSAGE);
            return correct;
        }

        if (!grade1.matches("[0-9]{1,2}(\\.[0-9]{1,2})?")
                || Double.parseDouble(grade1) < 0
                || Double.parseDouble(grade1) > 10
                || !grade2.matches("[0-9]{1,2}(\\.[0-9]{1,2})?")
                || Double.parseDouble(grade2) < 0
                || Double.parseDouble(grade2) > 10
                || !grade3.matches("[0-9]{1,2}(\\.[0-9]{1,2})?")
                || Double.parseDouble(grade3) < 0
                || Double.parseDouble(grade3) > 10) {

            JOptionPane.showMessageDialog(null, "Calicación inválida, las calificaciones deben tener el formato: 00.00; y deben estar en el rango [0-10]", "Error", JOptionPane.ERROR_MESSAGE);
            return correct;
        }

        correct = true;
        return correct;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchStudentjTextField = new javax.swing.JTextField();
        searchjButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentsjTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        insertjButton = new javax.swing.JButton();
        updatejButton = new javax.swing.JButton();
        deletejButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        idjTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        documentjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        namejTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lastNamejTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        grade1jTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        grade2jTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        grade3jTextField = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Clientes");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar"));

        jLabel1.setText("Buscar estudiante:");

        searchjButton.setText("Buscar");
        searchjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchStudentjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchjButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(searchStudentjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchjButton))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Estudiantes"));

        studentsjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        studentsjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentsjTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(studentsjTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestión"));

        insertjButton.setText("Insertar");
        insertjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertjButtonActionPerformed(evt);
            }
        });

        updatejButton.setText("Actualizar");
        updatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButtonActionPerformed(evt);
            }
        });

        deletejButton.setText("Borrar");
        deletejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletejButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("ID:");

        idjTextField.setEditable(false);

        jLabel3.setText("Documento:");

        jLabel4.setText("Nombre:");

        jLabel5.setText("Apellido:");

        jLabel6.setText("Calificación 1:");

        jLabel7.setText("Calificación 2:");

        jLabel8.setText("Calificación 3:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(insertjButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(updatejButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deletejButton))
                    .addComponent(idjTextField)
                    .addComponent(documentjTextField)
                    .addComponent(namejTextField)
                    .addComponent(lastNamejTextField))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(grade3jTextField))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(grade1jTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(grade2jTextField)))
                .addGap(124, 124, 124))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertjButton)
                    .addComponent(updatejButton)
                    .addComponent(deletejButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(grade1jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(documentjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(grade2jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(namejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(grade3jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lastNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchjButtonActionPerformed
        String searchTerm = searchStudentjTextField.getText().trim();
        loadStudents(searchTerm);
    }//GEN-LAST:event_searchjButtonActionPerformed

    private void insertjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertjButtonActionPerformed
        String id = idjTextField.getText().trim();
        String document = documentjTextField.getText().trim();
        String name = namejTextField.getText().trim();
        String lastName = lastNamejTextField.getText().trim();
        String grade1 = grade1jTextField.getText().trim();
        String grade2 = grade2jTextField.getText().trim();
        String grade3 = grade3jTextField.getText().trim();

        if (id.length() != 0) {

            JOptionPane.showMessageDialog(null, "No puede insertar", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!validateFields(document, name, lastName, grade1, grade2, grade3)) {
            return;
        }

        controller.setDocument(document);
        controller.setName(name);
        controller.setLastName(lastName);
        controller.setGrade1(Double.parseDouble(grade1));
        controller.setGrade2(Double.parseDouble(grade2));
        controller.setGrade3(Double.parseDouble(grade3));

        boolean result = model.insertStudents(controller);

        if (result) {
            JOptionPane.showMessageDialog(null, "Estudiante insertado", "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Estudiante no insertado", "Error", JOptionPane.ERROR_MESSAGE);
        }

        loadStudents("");
        cleanForm();

    }//GEN-LAST:event_insertjButtonActionPerformed

    private void studentsjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentsjTableMouseClicked
        int row = studentsjTable.getSelectedRow();

        String id = studentsjTable.getValueAt(row, 0).toString();
        String document = studentsjTable.getValueAt(row, 1).toString();
        String name = studentsjTable.getValueAt(row, 2).toString();
        String lastName = studentsjTable.getValueAt(row, 3).toString();
        String grade1 = studentsjTable.getValueAt(row, 4).toString();
        String grade2 = studentsjTable.getValueAt(row, 5).toString();
        String grade3 = studentsjTable.getValueAt(row, 6).toString();

        idjTextField.setText(id);
        documentjTextField.setText(document);
        namejTextField.setText(name);
        lastNamejTextField.setText(lastName);
        grade1jTextField.setText(grade1);
        grade2jTextField.setText(grade2);
        grade3jTextField.setText(grade3);
    }//GEN-LAST:event_studentsjTableMouseClicked

    private void updatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButtonActionPerformed
        String id = idjTextField.getText().trim();
        String document = documentjTextField.getText().trim();
        String name = namejTextField.getText().trim();
        String lastName = lastNamejTextField.getText().trim();
        String grade1 = grade1jTextField.getText().trim();
        String grade2 = grade2jTextField.getText().trim();
        String grade3 = grade3jTextField.getText().trim();

        if (id.length() == 0) {
            JOptionPane.showMessageDialog(null, "No puede actualizar", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!validateFields(document, name, lastName, grade1, grade2, grade3)) {
            return;
        }

        controller.setId(Integer.parseInt(id));
        controller.setDocument(document);
        controller.setName(name);
        controller.setLastName(lastName);
        controller.setGrade1(Double.parseDouble(grade1));
        controller.setGrade2(Double.parseDouble(grade2));
        controller.setGrade3(Double.parseDouble(grade3));

        boolean result = model.updateStudents(controller);

        if (result) {
            JOptionPane.showMessageDialog(null, "Estudiante actualizado", "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Estudiante no actualizado", "Error", JOptionPane.ERROR_MESSAGE);
        }

        loadStudents("");
        cleanForm();

    }//GEN-LAST:event_updatejButtonActionPerformed

    private void deletejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletejButtonActionPerformed
        String id = idjTextField.getText().trim();

        if (id.length() == 0) {
            JOptionPane.showMessageDialog(null, "Formulario vacío", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            controller.setId(Integer.parseInt(id));
            boolean result = model.deleteStudents(controller);

            if (result) {
                JOptionPane.showMessageDialog(null, "Estudiante eliminado", "Información", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Estudiante no eliminado", "Error", JOptionPane.ERROR_MESSAGE);
            }

            loadStudents("");
            cleanForm();
        }
    }//GEN-LAST:event_deletejButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deletejButton;
    private javax.swing.JTextField documentjTextField;
    private javax.swing.JTextField grade1jTextField;
    private javax.swing.JTextField grade2jTextField;
    private javax.swing.JTextField grade3jTextField;
    private javax.swing.JTextField idjTextField;
    private javax.swing.JButton insertjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNamejTextField;
    private javax.swing.JTextField namejTextField;
    private javax.swing.JTextField searchStudentjTextField;
    private javax.swing.JButton searchjButton;
    private javax.swing.JTable studentsjTable;
    private javax.swing.JButton updatejButton;
    // End of variables declaration//GEN-END:variables
}
